workflows:
    ionic-cordova-android-app:
        name: Ionic Cordova Android App
        environment:
            node: latest
        scripts: 
            - |
                # install dependencies and update to Cordova version 9
                npm install
                cvm install 9.0.0
                cvm use 9.0.0
            - |
                # Setup Cordova Android platform
                ionic cordova platform remove android --nosave
                ionic cordova platform add android --confirm --no-interactive --noresources
            - |
                # Build Android Cordova App
                script: ionic cordova build android --debug --no-interactive --device
        artifacts:
            - platforms/android/app/build/outputs/**/*.apk